### ISSUE TITLE
Add TOC to documentation

### ISSUE THREAD

**Issue by tomasbedrich** [bezirovoviku/document-generator#16] opened 2015-11-15 18:11 UTC
Almost every documentation I know has TOC. I think we should also include one into our page.

Examples:
- https://dev.twitter.com/overview/documentation
- https://developers.facebook.com/docs
- http://docs.docgen.apiary.io/

**Comment by SkaceKamen** [comment] 2015-11-15 18:26
This is duplicate of #13

**Closed by SkaceKamen** 2015-11-15 18:26 UTC
Labels: enhancement

**Comment by tomasbedrich** [comment] 2015-11-15 18:51
I don't see any mention about TOC in that issue.
